export const GET_ALL_PLAYERS = 'GET_ALL_PLAYERS';
export const GET_ALL_PLAYERS_ERROR = 'GET__PLAYERS_ERROR';
export const GET_ALL_PLAYERS_PENDING = 'GET_ALL_PLAYERS_PENDING';
export const GET_PLAYER = 'GET_PLAYER';
export const GET_PLAYER_ERROR = 'GET_PLAYER_ERROR';
export const GET_PLAYER_PENDING = 'GET_PLAYER_PENDING';